export const items = [
    {
        image:[new URL("@/images/productInfo/FDST001_YELLOW_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST001_YELLOW_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST001_YELLOW_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDST001_YELLOW_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST001_YELLOW_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST001_YELLOW_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDST001_YELLOW_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "TIE BACK BIKINI TOP YELLOW",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDST001Y",
        price: 89000,
        color: "Yellow",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Top"
    },
    {
        image:[new URL("@/images/productInfo/FDSB002_YELLOW_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_YELLOW_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_YELLOW_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDSB002_YELLOW_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_YELLOW_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_YELLOW_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDSB002_YELLOW_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "HIGH-RISE BRIEF YELLOW",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDSB002Y",
        price: 68000,
        color: "Yellow",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Bottom"
    },
    {
        image:[new URL("@/images/productInfo/FDSM001_YELLOW_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSM002_YELLOW_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSM002_YELLOW_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDSM001_YELLOW_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSM001_YELLOW_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSM002_YELLOW_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDSM002Y_YELLOW_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "TIE BACK MONOKINI YELLOW",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDSM001Y",
        price: 149000,
        color: "Yellow",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Monokini"
    },
    {
        image:[new URL("@/images/productInfo/FDST003_YELLOW_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST003_YELLOW_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST003_YELLOW_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDST003_YELLOW_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST003_YELLOW_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST003_YELLOW_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDST003_YELLOW_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "ONE SHOULDER CROP TOP YELLOW",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDST003Y",
        price: 80000,
        color: "Yellow",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Top"
    },
    {
        image:[new URL("@/images/productInfo/FDSB001_YELLOW_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB001_YELLOW_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB001_YELLOW_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDSB001_YELLOW_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB001_YELLOW_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB001_YELLOW_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDSB001_YELLOW_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "LOW-RISE BRIEF YELLOW",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDSB001Y",
        price: 68000,
        color: "Yellow",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Bottom"
    },
    {
        image:[new URL("@/images/productInfo/FDSB003_YELLOW_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB003_YELLOW_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB003_YELLOW_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDSB003_YELLOW_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB003_YELLOW_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB003_YELLOW_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDSB003_YELLOW_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "HIGH-RISE SHORTS YELLOW",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDSB003Y",
        price: 84000,
        color: "Yellow",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Bottom"
    },
    {
        image:[new URL("@/images/productInfo/FDST002_YELLOW_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST002_YELLOW_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST002_YELLOW_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDST002_YELLOW_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST002_YELLOW_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST002_YELLOW_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDST002_YELLOW_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "BANDEAU BIKINI TOP YELLOW",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDST002Y",
        price: 93000,
        color: "Yellow",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Top"
    },
    {
        image:[new URL("@/images/productInfo/FDSB003_YELLOW_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB003_YELLOW_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB003_YELLOW_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDSB003_YELLOW_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB003_YELLOW_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB003_YELLOW_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDSB003_YELLOW_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "HIGH-RISE SHORTS GREEN",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDSB003G",
        price: 84000,
        color: "Green",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Bottom"
    },
    {
        image:[new URL("@/images/productInfo/FDST002_GREEN_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST002_GREEN_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST002_GREEN_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDST002_GREEN_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST002_GREEN_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST002_GREEN_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDST002_GREEN_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "BANDEAU BIKINI TOP GREEN",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDST002G",
        price: 93000,
        color: "Green",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Top"
    },
    {
        image:[new URL("@/images/productInfo/FDSM001_GREEN_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSM001_GREEN_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSM001_GREEN_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDSM001_GREEN_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSM001_GREEN_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSM001_GREEN_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDSM001_GREEN_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "TIE BACK MONOKINI GREEN",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDSM001G",
        price: 149000,
        color: "Green",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Monokini"
    },
    {
        image:[new URL("@/images/productInfo/FDSB002_GREEN_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_GREEN_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_GREEN_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDSB002_GREEN_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_GREEN_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_GREEN_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDSB002_GREEN_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "HIGH-RISE BRIEF GREEN",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDSB002G",
        price: 68000,
        color: "Green",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Bottom"
    },
    {
        image:[new URL("@/images/productInfo/FDSB002_GREEN_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_GREEN_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_GREEN_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDSB002_GREEN_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_GREEN_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_GREEN_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDSB002_GREEN_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "ONE SHOULDER CROP TOP GREEN",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDST003G",
        price: 80000,
        color: "Green",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Top"
    },
    {
        image:[new URL("@/images/productInfo/FDSB001_GREEN_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB001_GREEN_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB001_GREEN_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDSB001_GREEN_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB001_GREEN_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB001_GREEN_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDSB001_GREEN_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "LOW-RISE BRIEF GREEN",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDSB001G",
        price: 68000,
        color: "Green",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Bottom"
    },
    {
        image:[new URL("@/images/productInfo/FDST001_GREEN_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST001_GREEN_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST001_GREEN_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDST001_GREEN_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST001_GREEN_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST001_GREEN_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDST001_GREEN_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "TIE BACK BIKINI TOP GREEN",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDST001G",
        price: 89000,
        color: "Green",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Top"
    },
    {
        image:[new URL("@/images/productInfo/FDSM001_BLUE_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSM001_BLUE_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSM001_BLUE_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDSM001_BLUE_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSM001_BLUE_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSM001_BLUE_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDSM001_BLUE_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "TIME BACK MONOKINI BLUE",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDSM001B",
        price: 149000,
        color: "Blue",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Monokini"
    },
    {
        image:[new URL("@/images/productInfo/FDST003_BLUE_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST003_BLUE_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST003_BLUE_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDST003_BLUE_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST003_BLUE_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST003_BLUE_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDST003_BLUE_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "ONE SHOULDER CROP TOP BLUE",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDST003B",
        price: 80000,
        color: "Blue",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Top"
    },
    {
        image:[new URL("@/images/productInfo/FDST001_BLUE_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST001_BLUE_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST001_BLUE_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDST001_BLUE_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST001_BLUE_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST001_BLUE_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDST001_BLUE_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "TIE BACK BIKINI TOP",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDST001B",
        price: 89000,
        color: "Blue",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Top"
    },
    {
        image:[new URL("@/images/productInfo/FDSB002_BLUE_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_BLUE_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_BLUE_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDSB002_BLUE_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_BLUE_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB002_BLUE_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDSB002_BLUE_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "HIGH-RISE BRIEF BLUE",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDSB002B",
        price: 68000,
        color: "Blue",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Bottom"
    },
    {
        image:[new URL("@/images/productInfo/FDSB001_BLUE_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB001_BLUE_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB001_BLUE_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDSB001_BLUE_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB001_BLUE_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB001_BLUE_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDSB001_BLUE_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "LOW-RISE BRIEF BLUE",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDSB001B",
        price: 68000,
        color: "Blue",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Bottom"
    },
    {
        image:[new URL("@/images/productInfo/FDST002_BLUE_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST002_BLUE_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST002_BLUE_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDST002_BLUE_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST002_BLUE_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDST002_BLUE_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDST002_BLUE_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "BANDAEU BIKINI TOP BLUE",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDST002B",
        price: 68000,
        color: "Blue",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Top"
    },
    {
        image:[new URL("@/images/productInfo/FDSB003_BLUE_1.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB003_BLUE_2.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB003_BLUE_3.jpg", import.meta.url).href, 
        new URL("@/images/productInfo/FDSB003_BLUE_4.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB003_BLUE_5.jpg", import.meta.url).href, new URL("@/images/productInfo/FDSB003_BLUE_6.jpg", import.meta.url).href ],
        longImage:[new URL("@/images/productDetail/FDSB003_BLUE_DETAIL.jpg", import.meta.url).href, new URL("@/images/productDetail/FOOTER_DETAIL.jpg", import.meta.url).href],
        text: "HIGH-RISE SHORTS BLUE",
        itemInfo: ["안정감있게 가슴을 감싸는 타이백 디자인의", "브이넥 비키니 탑입니다."],
        itemCode: "FDSB003B",
        price: 84000,
        color: "Blue",
        category: "Swimwear",
        material:"SHELL RECYCLED POLYAMIDE 80%, ELASTANE 20% / LINING RECYCLED POLYAMIDE 87%, ELASTANE 13%",
        part: "Bottom"
    }
]